Visualize
produdez/sparkimental pull request #6
Opened 2022-11-15 10:25 UTC by phoenisbuster

2022-11-15 11:36 UTC, produdez commented
1. Remove pptx file from this PR (add later after present is better i think).
2. Notebook file `visual.ipynb` is not enough. I remember mentioning that all graphs/visuals need to be output into picture files (put them in `/images` or `/output` folder)
3. Insights extracted from those visuals should be included in the notebook also. Ex:
 ```
For the pie chart (90-95 grade is the highest proportion of review score that given to the game. 
manymany extremely love the game gave it maxscore 100. Also, there few people dont really like it)
```
4. Something feels off about the `Top adj chart`
![image](https://user-images.githubusercontent.com/72970246/201909175-604e159e-0fa4-4cc6-809d-50e81a63b39e.png)
    
    - (Personal opinion) Should remove the **Common adjectives** like `full`, `old`, .. to really show the **DIFFERENT** adjectives from the two bracket
    - Could even make 3 graphs instead (common adj, low grade unique adj and high grade unique adj)
    - Also, if you notice, I dont think `fish` and `nintendo` are adjectives

2022-11-15 12:05 UTC, phoenisbuster commented
@RedEvilBK Please re-check the adj tokenize and export the images

2022-11-19 06:20 UTC, RedEvilBK commented
@produdez review plz

2022-11-19 11:42 UTC, produdez requested changes
Also, rename the `model-output.csv` back to `model-output.sample.csv` please. This is because each time we run our prediction pipeline, the result order will varies due to batching/parallelized

2022-11-19 11:42 UTC, produdez commented on sort_by_length.csv
> +Score,Review length
1. Put this in `/data`
2. Maybe better name if possible (`review_sorted_by_length`)

2022-11-19 11:42 UTC, produdez commented on Visualization_Final.ipynb
> +{
Recheck this file please, all of its content is gone

2022-11-19 15:07 UTC, RedEvilBK commented
- Rename back to animal-crossing.sample.csv
- Put sort_by_length.csv in /data
- Fix  .ipynb file 
@produdez  Review the last visualize_update plz & see if anything wrong?

2022-11-20 02:19 UTC, produdez approved these changes

2022-11-20 02:20 UTC, merged